global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'producer-service'
    static_configs:
      - targets: ['producer:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
  - job_name: 'consumer-service'
    static_configs:
      - targets: ['consumer:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: '/metrics'
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'
  - job_name: 'jaeger'
    static_configs:
      - targets:
          - 'jaeger:14269'
          - 'jaeger-query:16689'