server.name: "kibana"
server.host: "0.0.0.0"
server.port: 5601
elasticsearch.hosts: ["http://elasticsearch:9200"]
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long_for_encryption_purposes"